# Generated by Django 5.1.3 on 2024-12-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.TextField(unique=True)),
                ('birth', models.DateField(null=True)),
                ('join_date', models.DateField()),
            ],
        ),
    ]
