<<<<<<< HEAD
# Generated by Django 5.1.3 on 2024-11-22 15:04
=======
# Generated by Django 5.1.3 on 2024-11-22 19:52
>>>>>>> f04a13ea022b4250857879c6e19d9922c6002afc

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('email', models.TextField()),
                ('member_id', models.TextField()),
                ('join_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Member_informaiton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.TextField()),
                ('birth', models.DateTimeField()),
=======
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('birth', models.DateField()),
                ('join_date', models.DateField()),
>>>>>>> f04a13ea022b4250857879c6e19d9922c6002afc
            ],
        ),
    ]
